version: "3"
services:
  database:
    image: postgres:14-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password