spring:
  application:
    name: eventor

inventory-service:
  baseUrl: ${INVENTORY_SERVICE_BASE_URL}
  reservePath: /reserve

---
Spring:
  config:
    activate:
      on-profile: ["test"]

inventory-service:
  baseUrl: "inventory-service"
